###
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
  "username": "player1",
  "password": "password123" 
}

###
GET http://localhost:3001/api/sessions/current

###
DELETE http://localhost:3001/api/sessions/current

###
GET http://localhost:3001/api/network

###
GET http://localhost:3001/api/ranking

###
POST http://localhost:3001/api/games
Content-Type: application/json

{}

### 
GET http://localhost:3001/api/games/30

###
POST http://localhost:3001/api/games/31/submit
Content-Type: application/json

{
  "segments": [
    "7-14"
  ]
}